bind 0.0.0.0
protected-mode yes
dir /data
appendonly yes
appendfsync always
no-appendfsync-on-rewrite no
aof-load-truncated no
maxmemory-policy noeviction
maxmemory 512mb
save 900 1
stop-writes-on-bgsave-error yes
